begin
    declare sTime timestamp;
    set sTime = '20201015T17:10';
    
    SELECT 'LEVEL_1 EXIT_TO_PLAZA >>> LANE TO PLAZA TRANSFER PERFORMANCE' AS [SOURCE TO DESTINATION]
        ,MIN(datediff(SECOND, EXIT_TRXN_DTIME, PLAZA_INSERT_TIMESTAMP)) AS MIN_SEC
        ,AVG(datediff(SECOND, EXIT_TRXN_DTIME, PLAZA_INSERT_TIMESTAMP)) AS AVG_SEC
        ,MAX(datediff(SECOND, EXIT_TRXN_DTIME, PLAZA_INSERT_TIMESTAMP)) AS MAX_SEC
    
    FROM "DBA"."bos_direct_posting"
    WHERE EXIT_TRXN_DTIME > sTime UNION ALL
    
    SELECT 'LEVEL_2 PLAZA_TO_ZONE >>> PALZA TO ZONE TRANSFER PERFORMANCE' AS LEVEL
        ,MIN(datediff(SECOND, PLAZA_INSERT_TIMESTAMP, ZONE_INSERT_TIMESTAMP)) AS PLAZA_TO_ZONE_DIFF_MIN
        ,AVG(datediff(SECOND, PLAZA_INSERT_TIMESTAMP, ZONE_INSERT_TIMESTAMP)) AS PLAZA_TO_ZONE_DIFF_AVG
        ,MAX(datediff(SECOND, PLAZA_INSERT_TIMESTAMP, ZONE_INSERT_TIMESTAMP)) AS PLAZA_TO_ZONE_DIFF_MAX
    FROM "DBA"."bos_direct_posting"
    WHERE EXIT_TRXN_DTIME > sTime UNION ALL
    
    SELECT 'LEVEL_3 ZONE_TO_DP >>> ' AS LEVEL
        ,MIN(datediff(SECOND, ZONE_INSERT_TIMESTAMP, posted_TimeStamp)) AS ZONE_TO_DP_DIFF_MIN
        ,AVG(datediff(SECOND, ZONE_INSERT_TIMESTAMP, posted_TimeStamp)) AS ZONE_TO_DP_DIFF_AVG
        ,MAX(datediff(SECOND, ZONE_INSERT_TIMESTAMP, posted_TimeStamp)) AS ZONE_TO_DP_DIFF_MAX
    
    FROM "DBA"."bos_direct_posting"
    WHERE EXIT_TRXN_DTIME > sTime UNION ALL
    
    SELECT 'LEVEL_4 EXIT_TO_DP >>> LANE TO AMS PERFORMANCE' AS LEVEL
        ,MIN(datediff(SECOND, EXIT_TRXN_DTIME, posted_TimeStamp)) AS EXIT_TO_DP_DIFF_MIN
        ,AVG(datediff(SECOND, EXIT_TRXN_DTIME, posted_TimeStamp)) AS EXIT_TO_DP_DIFF_AVG
        ,MAX(datediff(SECOND, EXIT_TRXN_DTIME, posted_TimeStamp)) AS EXIT_TO_DP_DIFF_MAX
    
    FROM "DBA"."bos_direct_posting"
    WHERE EXIT_TRXN_DTIME > sTime UNION ALL

    SELECT 'LEVEL_5 REQUEST_PLAZA_TO_ZONE >>> ZONE SERVICE RESPONSE PERFORMANCE' AS LEVEL
        ,MIN(datediff(SECOND, request_TimeStamp, ZONE_INSERT_TIMESTAMP)) AS REQUEST_TO_ZONE_DIFF_MIN
        ,AVG(datediff(SECOND, request_TimeStamp, ZONE_INSERT_TIMESTAMP)) AS REQUEST_TO_ZONE_DIFF_AVG
        ,MAX(datediff(SECOND, request_TimeStamp, ZONE_INSERT_TIMESTAMP)) AS REQUESST_TO_ZONE_DIFF_MAX
    
    FROM "DBA"."bos_direct_posting"
    WHERE EXIT_TRXN_DTIME > sTime UNION ALL
    
   SELECT 'LEVEL_6 FETCHING_TO_AMS >>> FETCHING AND SENDING AMS RESPONSE PERFORMANCE' AS LEVEL
        ,MIN(datediff(SECOND, fetching_TimeStamp, posted_TimeStamp)) AS FETCH_TO_ZONE_DIFF_MIN
        ,AVG(datediff(SECOND, fetching_TimeStamp, posted_TimeStamp)) AS FETCH_TO_ZONE_DIFF_AVG
        ,MAX(datediff(SECOND, fetching_TimeStamp, posted_TimeStamp)) AS FETCH_TO_ZONE_DIFF_MAX
    FROM "DBA"."bos_direct_posting"
    WHERE EXIT_TRXN_DTIME > sTime
    
    
     
    ORDER BY [SOURCE TO DESTINATION];
    COMMIT;
    
    
    SELECT 'PLAZA '|| EXIT_PLAZA AS LEVEL, COUNT() AS AMOUNT
        ,MIN(datediff(SECOND, EXIT_TRXN_DTIME, PLAZA_INSERT_TIMESTAMP)) AS EXIT_TO_PLAZA_MIN
        ,AVG(datediff(SECOND, EXIT_TRXN_DTIME, PLAZA_INSERT_TIMESTAMP)) AS EXIT_TO_PLAZA_AVG
        ,MAX(datediff(SECOND, EXIT_TRXN_DTIME, PLAZA_INSERT_TIMESTAMP)) AS EXIT_TO_PLAZA_MAX
    
        ,MIN(datediff(SECOND, PLAZA_INSERT_TIMESTAMP, ZONE_INSERT_TIMESTAMP)) AS PLAZA_TO_ZONE_DIFF_MIN
        ,AVG(datediff(SECOND, PLAZA_INSERT_TIMESTAMP, ZONE_INSERT_TIMESTAMP)) AS PLAZA_TO_ZONE_DIFF_AVG
        ,MAX(datediff(SECOND, PLAZA_INSERT_TIMESTAMP, ZONE_INSERT_TIMESTAMP)) AS PLAZA_TO_ZONE_DIFF_MAX
    
    FROM "DBA"."bos_direct_posting"
    WHERE EXIT_TRXN_DTIME > '20201016T07:00'
    GROUP BY EXIT_PLAZA 
    ORDER BY EXIT_PLAZA;
    
    
    COMMIT;

    
     SELECT EXIT_PLAZA, COUNT() AS SAY
    , MIN(EXIT_TRXN_DTIME) AS ILK_EXIT
    , MAX(EXIT_TRXN_DTIME) AS SON_EXIT
 
    , MIN(posted_TimeStamp) AS ILK_post
    , MAX(posted_TimeStamp) AS SON_post
 
  
 FROM bos_direct_posting
 WHERE ENTRY_PLAZA is not null 
--and EXIT_TRXN_DTIME BETWEEN '20201015T17:00' and getdate() --'20201015T17:50'
 and posted_TimeStamp is not null
-- and exit_plaza <> 118
GROUP BY EXIT_PLAZA
 ORDER BY EXIT_PLAZA --EXIT_TRXN_DTIME
 ;
  
COMMIT;
end
